"""
schema.py

Módulo interno del pipeline IAR (Mastercard) — define el layout de columnas
de salida (orden final) de la tabla IP0040T1 (rangos de BIN/reglas), usado
por `clean.py` (`clean_ip0040t1`) para completar columnas faltantes y
reordenar el DataFrame antes de escribirlo a S3.
"""

IP0040T1_OPERATIONAL_COLUMNS = [
    "app_customer_code",
    "app_type_file",
    "app_hash_file",
    "app_processing_date",
    "app_full_data",
    "app_header_type",
    "alm_activation_date",
    "durbin_regulated_rate_indicator",
    "moneysend_indicator",
    "repower_reload_participation_indicator",
    "cashback_without_purchase_indicator",
    "psn_route_indicator",
    "regulated_rate_type",
    "contactless_enabled_indicator",
    "merchant_cleansing_activation",
    "merchant_cleansing_service",
    "spend_control_switch",
    "effective_timestamp",
    "active_inactive_code",
    "table_id",
    "low_range",
    "gcms_product",
    "high_range",
    "card_program_identifier",
    "card_program_priority",
    "member_id",
    "product_type",
    "endpoint",
    "card_country_alpha",
    "card_country_numeric",
    "region",
    "product_class",
    "tran_routing_ind",
    "first_present_reassign_ind",
    "product_reassign_switch",
    "pwcb_optin_switch",
    "mapping_service_ind",
    "co_brand_participation_switch",
    "floor_expiration_date",
    "chip_to_magnetic",
    "cardholder_billing_primary_currency",
    "cardholder_billing_currency_exponent_default",
    "cardholder_billing_currency_default",
    "alm_participation_ind",
    "issuer_account_range_gaming_participation_indicator",
    "pay_by_account_indicator",
    "cardholder_currency_indicator",
    "anonymous_prepaid_indicator",
    "faster_funds_indicator",
    "licensed_product_id",
    "non_reloadable_prepaid_switch",
    "meal_voucher_indicator",
    "post_date_service_indicator",
    "issuer_target_market_participation_indicator",
    "authenticator_indicator",
    "cash_access_only_participating_indicator",
    "app_date_end",
    "app_date_valid",
    "app_creation_date",
]
